name: painel_administrativo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1
  supabase_flutter: ^2.9.0
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  file_picker: ^10.2.0
  open_filex: ^4.7.0
  intl: ^0.18.1
  google_fonts: ^6.2.1
  diacritic: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.2.5
  fl_chart: ^0.65.0
  bcrypt: ^1.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.4 
  percent_indicator: ^4.2.2



flutter:
 uses-material-design: true
 assets:
    - images/
    - .env

flutter_native_splash:
  color: "#00358E"
  image: images/logoEuroProWhite.png
  android: true
  ios: true

flutter_icons:
  image_path: images/logoEuroProWhite.png
  ios: true
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: images/logoEuroProWhite.png
